language: java
jdk:
- oraclejdk8
sudo: false
before_install: 
  - git submodule update --init --recursive
  - cd ratpack && ./gradlew install -x test && cd ..
install: ./gradlew clean check
after_success:
- ./gradlew jacocoTestReport coveralls
env:
  global:
    secure: nz6bM3mrB3xzlKJPdglIfGDF/3PLO5M4H+oXQqHqFFQm3W/DL0ixolzbTQpytKvrOO88fi9MFKnb9dnbOXRSIL2VnGwnpwNcOJYOGhNQA/TgXnVApTX4Jh/uHNziiRJ8UsvkYnFt0gIBrV2jgejK+AVeKzVuwGEryXbkwv7Gmkpd4qECjQ+94YcVqUL7zpMMU0Lsbk5kVNciW8hQijiqr+te9YPOBG0S6gNENZ01NDSwBAXHCJ3TvvUn3V62GGEO1tGelLXLld//ZPFruJ3mH/Uc3vYWFdk524ARLNSpxBiKkWOxQHeD8DdfT+NbLkT85mynPzJeRIlpr+Ndo52IK1fm0peNiQYNX9UNCGgxL3j8MytpzeB6uqE1JZoYNxwUmqUhk+sezpoz+G4/kg02EkNuR+O5JFqgVX0Mg1uRAIOKW19otk7fMjwhbwJ/IKPlrAj7fPPV5Sms4WGCvgUkB2dxB5eh72JocYZuncO+tPxxrkYSJ5/9VwOIVi1behmRYCvAPn2UESbpCRRP8I7WwIXHlpgwDy7qDRyShNAY0Ls2FFvoapj+yTSBB84Z4aiMaq/+AR1R/5D/5gfZ2r8s3Acv1zkjs9iQ+vdC6hG73KC9LSWJI39Jh42Cz4Lj/pHHQ9ovkvelfaraykyb4v2eXLBA6ELzaW6Hf8ng7A3VrdY=
